### ISSUE TITLE
Does this module help me create all combinations from lists?

### ISSUE THREAD

**Issue by amitaibu** [Janiczek/elm-list-cartesian#1]
Hi @Janiczek :wave:

I have a list of lists with different lengths. In this example I have a list holding 3 lists:

```
 [ [ 1, 2] [a, b, c] [10, 20, 30, 40, 50] ]
```

I'd like to get all the permmutations. That is, something like:

```
[

[1, a, 10]
[2, a, 10]
[1, b, 10]
[2, b, 10]
[1, c, 10]
[2, c, 10]
[2, c, 20]
-- ...
]
```

**Comment by Janiczek** [comment]
Hello @amitaibu !
The module in principle does _this kind of stuff_ but if you're holding things in a list of lists, you'll be better served by [`List.Extra.cartesianProduct`](https://package.elm-lang.org/packages/elm-community/list-extra/latest/List-Extra#cartesianProduct) which has that exact API!

See this Ellie :)
https://ellie-app.com/gMp7gQjLD8ja1

**Comment by Janiczek** [comment]
Just to compare, List.Cartesian has a little different API - it needs you to give it the inner lists one by one, and gives the choices for each separately too (`\a b c -> ...` instead of in a list):
https://ellie-app.com/gMpfcWng6fna1

**Comment by amitaibu** [comment]
Perfect, thank you!
